### ISSUE TITLE
missing feeCurrency on closed orders

### ISSUE THREAD

**Issue by khoan** [coinsuperapi/API_docs_en#1]
as documented at https://github.com/coinsuperapi/API_docs_en/wiki#28-query-personal-order-history feeCurrency should be present in fetched orders but is missing.

**Comment by coinsuperapi** [comment]
Hi, khoan. As documented at https://github.com/coinsuperapi/API_docs_en/wiki#28-query-personal-order-history, feeCurrency and fee depend on each trade detail. They are in each trade detail.
