### ISSUE TITLE
why does market endpoint require credentials?

### ISSUE THREAD

**Issue by khoan** [coinsuperapi/API_docs_en#2]
Shouldn't these "market" endpoints be accessible without access key?

```
{
    "common":{
        "accesskey" : "1900000109",            // Access Key
        "timestamp": "1500000000000",            // Timestamp
        "sign":"sdfsdfa1231231sdfsdfsd"        // MD5 Signature
    },
...
```

/api/v1/market/depth
/api/v1/market/orderBook
/api/v1/market/kline
/api/v1/market/tickers
/api/v1/market/symbolList

**Comment by coinsuperapi** [comment]
For the better service for certified users.
