### ISSUE TITLE
/api/v1/order/tradeHistory is broken

### ISSUE THREAD

**Issue by khoan** [coinsuperapi/API_docs_en#4]
we used to pass these params: `{ symbol: 'WIB/BTC', size: 100, utcStart: 1559022336548 }`, but got error: `{ Error: coinsuper {"code":"2002","data":{},"msg":"illegal argument. data.utcEndmay not be empty"}`

Then I tried `{ symbol: 'WIB/BTC',  size: 100,  utcStart: 1559022380637,  utcEnd: 1560231980637 }` but got error `{ Error: coinsuper {"code":"2005","data":{},"msg":"parameter is invalid"}`

Please advice.

**Comment by coinsuperapi** [comment]
According to the latest API document https://www.coinsuper.com/api/docs/v1/api_en.html#3-6-query-personal-trade-history , The utcStart and utcEnd span shall not exceed one week. If you intend to query 
the data one week before, please subtract the corresponding time from utcStart and utcEnd at the same time.
